module.exports = {
  STATUS_CODE: {
    OK: 200,
    TRIPLEA: 151,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    INFO: 250,
    NON_AUTHORITATIVE: 203,
    BAD_REQUEST: 400,
    UN_AUTHORIZED: 401,
    FORBIDDEN: 403,
    RESOURCE_NOT_FOUND: 404,
    PROXY_AUTH_FAILED: 412,
    TOO_MANY_REQUESTS: 429,
    VALIDATION_FAILURE: 450,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
    SERVER_TIMEOUT: 504,
  },
  ERROR_MSGS: {
    INTERNAL_SERVER_ERROR: "Unable to process,Please Try Again",
    APPROVER_UN_AUTHORIZED: "You are not Authorized for Process Approve",
    CREATE_ERROR: "Collection Not Create",
    ACCOUNT_EMAIL_EXISTS: "Email already exists. Please login",
    PLATFORM_EXISTS: "Platform already exists!!",
    FORM_EXISTS: "data already exists!!",
    ACCOUNT_MOBILE_EXISTS: "Mobile already exists. Please login",
    MOBILE_NOT_FOUND: "Mobile No Not Found",
    ROLE_EXISTS: "Role already exists",
    ROLE_EXISTS: "Role already exists",
    MODULE_EXISTS: "Module already exists",
    MODULE_TITLE: "Module Not exists",
    CONVERTED: "Lead already Converted",
    GROUP_EXISTS: "Group already exists",
    ROLE_NOT_EXISTS: "Role Not exists",
    UN_AUTHORIZED: "Unauthorized User",
    ORGANIZATION_EXISTS: "Organization already exists. Please login",
    ORGANIZATION_NOTEXISTS: "Organization not exists. Please register organization",
    ACCOUNT_DISABLED:
      "Your account has been disabled, please reach out to our support",
    YOUR_PACK_EXPIRED: "Your subscription has expired",
    YOUR_PACK_NOT_FOUND:
      "Your Subscription Package Not Found!! Please Contact Support",
    YOUR_PACK_USER_LIMIT_USED: "Your Subscription User Count limit Used",
    ACCOUNT_NOT_FOUND: "Account not found",
    PLATFORM_NOT_FOUND: "Platform not found",
    DATA_NOT_FOUND: "Data not found",
    DATA_ALREADY_CONVERT: "Data Already convert",
    ACCOUNT_BLOCKED:
      "Your account has been blocked, please reach out to our support",
    ACCOUNT_LOCKED:
      "Your account has been blocked, please use forgot password option to reset password and login.",
    ACCOUNT_LOCKED_EMAIL_TRIGGERED:
      "Your account has been blocked, mail has been triggered to reset password.",
    IP_LOCKED: "Please try again later.",
    INVALID_LOGIN: "Invalid email or/and password.",
    USER_NOT_FOUND: "User not found",
    WALLET_NOT_FOUND: "Account not found, related to the given wallet.",
    LOGIN_WITH_EMAIL: "Please login with Email and password",
    LOGIN_WITH_GOOGLE: "Please login with Google",
    FORGOT_PASSWORD_TOKEN_EXPIRED: "Token has expired.",
    TOKEN_MISSING: "No token provided",
    TOKEN_SESSION_EXPIRED: "Token Session Expired",
    INVALID_TOKEN_FORMAT: "Token invalid format",
    INVALID_TOKEN_TYPE: "Invalid Token type",
    INVALID_OBJECT_ID: "Invalid Value",
    INVALID_CODE: "Invalid Code",
    INVALID_OTP: "Invalid OTP",
    INVALID_TOKEN_ID: "Invalid Token Id",
    GOOGLE_AUTHENTICATION_FAILED:
      "Google authentication failed. Please try again.",
    LINKEDIN_AUTHENTICATION_FAILED:
      "Linkedin authentication failed. Please try again.",
    NOT_HAVE_A_SUFFICIENT_WALLET_AMOUNT: "Not Have A Sufficent Wallet Amount",
  },
  INFO_MSGS: {
    NO_DATA: "No data found",
    NO_ENCRYPT: "Encryption not match",
    CREATED_SUCCESSFULLY: "Created successfully",
    DOWNLOADED_SUCCESSFULLY: "Data Downloaded Successfully",
    ACTIVET_SUCCESSFULLY: "User Successfully Activated!!",
    UNACTIVET_SUCCESSFULLY: "User Successfully UnActivated!!",
    UPDATED_SUCCESSFULLY: "Updated successfully",
    DELETE_SUCCESSFULLY: "Delete successfully",
    SUCCESS: "Request Success",
    SUCCESSFUL_REGISTER:
      "Your registration with Brant Ford India is successful.",
    SUCCESSFUL_UPDATE: "Successfully updated",
    WELCOME_MSG: "Welcome to Client API Services_v4.",
    SUCCESSFUL_LOGIN: "Successfully logged in.",
    SUCCESSFUL_ENABLE: "2FA enabling requested successfully.",
    SUCCESSFUL_RESET: "2FA is successfully reset on your request.",
    PASSWORD_CHANGED: "Your password has been changed successfully.",
    VERIFICATION_EMAIL: "Verification Email send successfully.",
    VERIFICATION_OTP: "Verification OTP send successfully.",
    VERIFICATION_OTP_RESEND: "OTP Resend send successfully.",
    USER_CREATED: "User Created successfully.",
    PLATFORM_CREATED: "Platform Created successfully.",
    EMAIL_NOT_VERIFIED: "Email not verified, Please verify it.",
    EMAIL_VERIFIED: "Email already Verified. Please login",
    OTP_VERIFIED: "OTP already Verified. Please login",
    SUCCESSFUL_OTP_VERIFIED: "OTP Successfully Verified",
    EMAIL_SEND: "Email sent to the registered account.",
    ACCOUNT_VERIFIED: "Your account has been verified, Please login.",
    TWO_FACTOR_SUCCESS: "Successfully configured 2FA",
    TWO_FACTOR_ENABLED: "2FA enabled successfully",
    TWO_FACTOR_DISABLED: "2FA disabled successfully",
    SUCCESSFUL_LOGOUT: "Successfully logged out.",
    USERNAME_AVAILABLE: "Username available",
    USERNAME_NOT_AVAILABLE: "Username not available",
    TRAN_NOT_AVAILABLE: "Wallet Transaction Not Available",
    ALREADY_VIEWED: "You have already viewed the Building",
    VIEW_ADDED: "Successfully updated view",
    ALREADY_TRACK: "You have already track the Building",
    REMOVE_TRACK: "You have remove track the Building",
    TRACK_ADDED: "Successfully updated track",
    READ_SUCCESSFULLY: "Read",
    MSG_REQUIRED: "is required",
    NOTIFICATION_NOT_FOUND: "Notification Not Found",
  },
};
