trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- script: |
    echo "This is a placeholder step; no changes are made."
  displayName: 'No-op step'

# Snyk Security Scan for Application Dependencies
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snykoattacko'
    testType: 'app'
    targetFile: 'package.json'
    monitorWhen: 'always'
    failOnIssues: false
    projectName: 'calculator-project/Backend'
    organization: 'f6ff1f1e-b60e-43aa-91ab-fad13fbc3519'
    reportFormat: 'html'
    reportFile: '$(Build.ArtifactStagingDirectory)/snyk-app-report.html'
  displayName: 'Run Snyk App Scan'

- task: dependency-check-build-task@6
  inputs:
    projectName: 'crm'
    scanPath: '*.json'
    format: 'XML, HTML'
    uploadReports: true
    warnOnCVSSViolation: true
    enableExperimental: true
    nvdApiKey: '66ead14b-79d0-48e5-a3cb-8f0f0aa40bda'
    localInstallPath: '.'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/dependency-check-report.xml'  # Adjust this path to your report location
    failTaskOnFailedTests: false
    testRunTitle: 'Dependency Check Report'

  
- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'sonar-connection'
    organization: 'demodevopsyl'
    scannerMode: 'cli'
    cliScannerVersion: '6.2.1.4610'
    configMode: 'manual'
    cliProjectKey: 'davidputra2812_CRM-Backend'
    cliProjectName: 'CRM Backend'
    cliSources: '.'

- task: SonarCloudAnalyze@3

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'crmrepo'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: '$(Build.BuildNumber)'

