name: VAPT Workflow

on:
  push:
    branches: [ master ]

jobs:
  vapt:
    name: Vulnerability Assessment and Penetration Testing
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Code Review with CodeClimate
      env:
        CC_REPORTER_ID: ${{ secrets.CC_REPORTER_ID }}
      run: |
        echo "Running Code Review with CodeClimate..."
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
        ./cc-test-reporter after-build --exit-code $?
        
    - name: Run GitLeaks
      run: |
        echo "Scanning for secrets with GitLeaks..."
        docker run --rm --name=gitleaks --volume $(pwd):/code zricethezav/gitleaks:latest detect --source=/code

    - name: Run Talisman
      run: |
        echo "Running Talisman for security checks..."
        npm install -g talisman
        talisman --scan

    - name: Run SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        echo "Running static analysis with SonarQube..."
        sonar-scanner \
          -Dsonar.projectKey=my_project_key \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarqube.example.com \
          -Dsonar.login=$SONAR_TOKEN
